# Generated by the gRPC Python protocol compiler plugin.
"""Client and server classes for the System Firmware service."""

import grpc

import iot2050_system_firmware_pb2 as system_firmware_pb2


class SystemFirmwareStub:
    """Client for the System Firmware gRPC service."""

    def __init__(self, channel):
        self.GetCapabilities = channel.unary_unary(
            "/iot2050.systemfirmware.SystemFirmware/GetCapabilities",
            request_serializer=system_firmware_pb2.Empty.SerializeToString,
            response_deserializer=system_firmware_pb2.CapabilitiesReply.FromString,
        )
        self.Inspect = channel.unary_unary(
            "/iot2050.systemfirmware.SystemFirmware/Inspect",
            request_serializer=system_firmware_pb2.InspectRequest.SerializeToString,
            response_deserializer=system_firmware_pb2.InspectionReply.FromString,
        )
        self.Update = channel.unary_unary(
            "/iot2050.systemfirmware.SystemFirmware/Update",
            request_serializer=system_firmware_pb2.UpdateRequest.SerializeToString,
            response_deserializer=system_firmware_pb2.OperationReply.FromString,
        )
        self.InspectRollback = channel.unary_unary(
            "/iot2050.systemfirmware.SystemFirmware/InspectRollback",
            request_serializer=system_firmware_pb2.RollbackRequest.SerializeToString,
            response_deserializer=system_firmware_pb2.RollbackReply.FromString,
        )
        self.Rollback = channel.unary_unary(
            "/iot2050.systemfirmware.SystemFirmware/Rollback",
            request_serializer=system_firmware_pb2.RollbackRequest.SerializeToString,
            response_deserializer=system_firmware_pb2.OperationReply.FromString,
        )


class SystemFirmwareServicer:
    """Base class for System Firmware service implementations."""

    def GetCapabilities(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Inspect(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InspectRollback(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Rollback(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SystemFirmwareServicer_to_server(servicer, server):
    handlers = {
        "GetCapabilities": grpc.unary_unary_rpc_method_handler(
            servicer.GetCapabilities,
            request_deserializer=system_firmware_pb2.Empty.FromString,
            response_serializer=system_firmware_pb2.CapabilitiesReply.SerializeToString,
        ),
        "Inspect": grpc.unary_unary_rpc_method_handler(
            servicer.Inspect,
            request_deserializer=system_firmware_pb2.InspectRequest.FromString,
            response_serializer=system_firmware_pb2.InspectionReply.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=system_firmware_pb2.UpdateRequest.FromString,
            response_serializer=system_firmware_pb2.OperationReply.SerializeToString,
        ),
        "InspectRollback": grpc.unary_unary_rpc_method_handler(
            servicer.InspectRollback,
            request_deserializer=system_firmware_pb2.RollbackRequest.FromString,
            response_serializer=system_firmware_pb2.RollbackReply.SerializeToString,
        ),
        "Rollback": grpc.unary_unary_rpc_method_handler(
            servicer.Rollback,
            request_deserializer=system_firmware_pb2.RollbackRequest.FromString,
            response_serializer=system_firmware_pb2.OperationReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "iot2050.systemfirmware.SystemFirmware", handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
