#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ] || [ "$1" = "deconfigure" ]; then
    deb-systemd-invoke stop 'iot2050-module-firmware.service' >/dev/null 2>&1 || true
    deb-systemd-helper disable 'iot2050-module-firmware.service' >/dev/null 2>&1 || true
fi
