# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot2050-module-firmware.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1diot2050-module-firmware.proto\x12\x16iot2050.modulefirmware\"\x07\n\x05\x45mpty\"m\n\x11\x43\x61pabilitiesReply\x12\x11\n\tsupported\x18\x01 \x01(\x08\x12\x11\n\tmax_slots\x18\x02 \x01(\x05\x12\x18\n\x10\x63hip_a_supported\x18\x03 \x01(\x08\x12\x18\n\x10\x63hip_b_supported\x18\x04 \x01(\x08\",\n\x0eInspectRequest\x12\x0c\n\x04slot\x18\x01 \x01(\x05\x12\x0c\n\x04scan\x18\x02 \x01(\x08\"[\n\x0eSlotInspection\x12\x0c\n\x04slot\x18\x01 \x01(\x05\x12\x11\n\tavailable\x18\x02 \x01(\x08\x12\x13\n\x0b\x63hip_a_node\x18\x03 \x01(\x08\x12\x13\n\x0b\x63hip_b_node\x18\x04 \x01(\x08\"s\n\x0fInspectionReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x35\n\x05slots\x18\x04 \x03(\x0b\x32&.iot2050.modulefirmware.SlotInspection\"E\n\rUpdateRequest\x12\x0c\n\x04slot\x18\x01 \x01(\x05\x12\x12\n\nfirmware_a\x18\x02 \x01(\x0c\x12\x12\n\nfirmware_b\x18\x03 \x01(\x0c\"?\n\nChipResult\x12\x11\n\tattempted\x18\x01 \x01(\x08\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\xe0\x01\n\x0bUpdateReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04slot\x18\x04 \x01(\x05\x12\x32\n\x06\x63hip_a\x18\x05 \x01(\x0b\x32\".iot2050.modulefirmware.ChipResult\x12\x32\n\x06\x63hip_b\x18\x06 \x01(\x0b\x32\".iot2050.modulefirmware.ChipResult\x12\x17\n\x0fpartial_failure\x18\x07 \x01(\x08\x12\x17\n\x0freboot_required\x18\x08 \x01(\x08\x32\xa5\x02\n\x0eModuleFirmware\x12]\n\x0fGetCapabilities\x12\x1d.iot2050.modulefirmware.Empty\x1a).iot2050.modulefirmware.CapabilitiesReply\"\x00\x12\\\n\x07Inspect\x12&.iot2050.modulefirmware.InspectRequest\x1a\'.iot2050.modulefirmware.InspectionReply\"\x00\x12V\n\x06Update\x12%.iot2050.modulefirmware.UpdateRequest\x1a#.iot2050.modulefirmware.UpdateReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot2050_module_firmware_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=57
  _EMPTY._serialized_end=64
  _CAPABILITIESREPLY._serialized_start=66
  _CAPABILITIESREPLY._serialized_end=175
  _INSPECTREQUEST._serialized_start=177
  _INSPECTREQUEST._serialized_end=221
  _SLOTINSPECTION._serialized_start=223
  _SLOTINSPECTION._serialized_end=314
  _INSPECTIONREPLY._serialized_start=316
  _INSPECTIONREPLY._serialized_end=431
  _UPDATEREQUEST._serialized_start=433
  _UPDATEREQUEST._serialized_end=502
  _CHIPRESULT._serialized_start=504
  _CHIPRESULT._serialized_end=567
  _UPDATEREPLY._serialized_start=570
  _UPDATEREPLY._serialized_end=794
  _MODULEFIRMWARE._serialized_start=797
  _MODULEFIRMWARE._serialized_end=1090
# @@protoc_insertion_point(module_scope)
