#!/bin/sh
#
# Copyright (c) Siemens AG, 2026
#
# Authors:
#  Li Hua Qian <huaqian.li@siemens.com>
#
# SPDX-License-Identifier: MIT
#

set -eu

install -d -m 700 /var/lib/faillock

if [ -f /usr/share/iot2050-pam-conf/lock-root-password ]; then
    passwd -l root
fi

pam-auth-update --package --enable \
    iot2050-failed-login-preauth \
    iot2050-failed-login-lockout \
    iot2050-failed-login-success \
    iot2050-password-quality